### ISSUE TITLE
Multiple evaluations for one course

### ISSUE THREAD

**Issue by He3lixxx** [fsr-de/EvaP#1047]
For each course, we should be able to have multiple evaluations. This feature should be done after the results rework (#571) because it's not possible with the current UI.

Use cases:
- Evaluation during the semester so the lecturer can directly react to feedback
- Evaluation of the exam after the main evaluation finished so the lecturers can get feedback on the exam. This required knowledge of the exam dates, which we don't currently have

**Comment by janno42** [comment]
see also https://github.com/fsr-itse/EvaP/wiki/Feature-Ideas

**Comment by janno42** [comment]
The proposed approach is as follows:
Current `Course`s will be split into `Course`s which will only hold meta-information about the actual course (like name, degree, participants, ...) and `Evaluation`s which hold the course questionnaires and contributions as well as the evaluation periods. Each `Course` can have multiple `Evaluation`s.

Most views for staff, contributors and students will have to be updated. Only staff will be able to edit `Course` information, editors will only be able to change `Evaluation` data during their review.
Results pages will be per `Evaluation`. On an `Evaluation`'s result page other results pages belonging to the same `Course` should be linked (e.g., by adding navigation arrows on the left and right side of the page).

We still have to decide how multiple `Evaluation`s of one `Course` will be displayed on the staff, contributor and student index pages and on the results overview page.

**Comment by janno42** [comment]
done in #1300
