### ISSUE TITLE
Inline datatables localization files to speed up first paint

### ISSUE THREAD

**Issue by karyon** [fsr-de/EvaP#1103]
Right now, datatables gets the localization file in form of a URL (see [datatables.html](https://github.com/fsr-itse/EvaP/blob/master/evap/evaluation/templates/datatables.html)), that is, it starts an ajax request when it starts processing the tables, and waits with processing until the result has been received.

both locales should be included into the compressed javascript or inlined into the html template so they are loaded earlier.

we do something similar for the [bootstrap datetimepicker](https://github.com/fsr-itse/EvaP/blob/028b6301e3eed446d93ae8675030d82c68d46886/evap/evaluation/templates/bootstrap_datetimepicker.html). unfortunately, it's not that easy in this case, since the localization files are json files, not javascript files.

one approach would be to turn the json files to js files, and simply putting the datastructure inside into a variable with the name of the corresponding locale.

**Comment by janno42** [comment]
i'm currently working on completely removing the datatables from the results pages so this might become obsolete.

**Comment by karyon** [comment]
we are using datatables on other pages as well.

**Comment by janno42** [comment]
We can maybe replace those as well...
