### ISSUE TITLE
Form Submit Error when selecting voting answer using spacebar

### ISSUE THREAD

**Issue by felixrindt** [fsr-de/EvaP#1199]
When tabbing through questions and selecting an option using the spacebar, it visually looks correct, but on form submit I get an error (Firefox 61 and most recent Opera).

![screenshot from 2018-06-05 15-42-54](https://user-images.githubusercontent.com/5970076/40979872-55bc9bd2-68d7-11e8-8917-0d3adee9914c.png)

Related to #1134

**Comment by He3lixxx** [comment]
This is a bootstrap bug, as you can also see on their documentation page here: https://getbootstrap.com/docs/4.1/components/buttons/#checkbox-and-radio-buttons. If you inspect one of these radio buttons and remove the clip style, you can see which input gets selected. When you change your selection using a keyboard, the corresponding radio input will not be selected.

There is a "fix" proposed here: https://stackoverflow.com/questions/29090108/bootstrap3-radio-button-not-working-with-keyboard
There are also several issues and pull requests on the bootstrap github, the most up to date seems to be this one where someone commented 2 days ago that he is experiencing the same issue: https://github.com/twbs/bootstrap/issues/18874
