### ISSUE TITLE
Django 2.1 upgrade

### ISSUE THREAD

**Issue by karyon** [fsr-de/EvaP#1244]
https://docs.djangoproject.com/en/2.1/releases/2.1/

There is a guide for upgrading: https://docs.djangoproject.com/en/2.1/howto/upgrade-version/

Basically
* Read the release notes
* update dependencies
* run tests with `python -Wa` and solve deprecation warnings
* put the new django into the requirements
* run tests, fix failures if any
* run tests with `python -Wa` and solve deprecation warnings again
* if there was any new feature in the release notes that might help us, use it

also, we need to check the installed python version on production, django 2.1 supports python 3.5 and newer.

**Comment by janno42** [comment]
production is currently running python 3.5, so that's fine.

**Comment by jkhlr** [comment]
@janno42 @karyon @He3lixxx could somebody assign me here? :)
