### ISSUE TITLE
configure TravisCI and Codacy to support python 3.5

### ISSUE THREAD

**Issue by jkhlr** [fsr-de/EvaP#1272]
Currently, tests are failing on TravisCI if python `3.5` features (like f-strings) are used, since it currently seems to execute the tests with python `3.4.6`. Same for Codacy (f-strings are considered a syntax error there)
On the production instance, python `3.5` seems to be available (https://github.com/fsr-itse/EvaP/issues/1244#issuecomment-417714795), and `3.5` is also the python version in the vagrant environment, so I guess it would make sense to update the CI pipeline accordingly.

**Comment by jkhlr** [comment]
@karyon You are right, f-strings came with python `3.6`. I checked again the version of the python interpreter in the vagrant VM and it is actually `3.6.3`. So if we could enable python `3.6`/`3.7` on the production instance, it would be even better :)

**Comment by janno42** [comment]
You can assume 3.7 to be available.

**Comment by jkhlr** [comment]
feel free to assign me here :)

**Comment by janno42** [comment]
we're now using python 3.7 in travis (#1282) and are waiting for codacy to support it as well.
