### ISSUE TITLE
Add degrees to result export

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1274]
The result export should include the degree and course type for each course in separate lines in the excel sheet right below the title of the course.

Furthermore, it should be possible to select for which degrees the results shall be exported. In addition to the current course type selection a degree selection needs to be added. A course will then be included in a specific sheet if it is in one of the selected degrees *and* in one of the selected course types.

**Comment by karyon** [comment]
regarding the export part, the exporter is kind of hard to read, but the actual change should be small. in the exporter there's a small loop that iterates over all courses and outputs their names (the exporter works line by line!), and below that, another loop would have to be added that outputs the degree.

regarding the degree selection, that should work analogously to the course type selection.

**Comment by janno42** [comment]
@Irliung do you still want to work on this or shall i remove your assignment?
