### ISSUE TITLE
Code duplication in evap/staff/templates/staff_user_merge.html 

### ISSUE THREAD

**Issue by He3lixxx** [fsr-de/EvaP#1299]
In #1294 we came across some code duplication in evap/staff/templates/staff_user_merge.html. We may want to refactor that.

**Comment by foodplanet** [comment]
Before starting to refactor from the top we should think about the general structure of the tables rows/for loops.

**Comment by He3lixxx** [comment]
I talked to @janno42 and we agreed that it's probably a good idea to somehow follow the standard approach for dynamically filling a table: The header row will be rendered in the template, and we pass a list of something (probably tuples?) that represents a row. The template will loop over them and add a row for each iteration. This is easy for the first few rows, as there are only simple string, but becomes more complex when the group badges are rendered, user names are concatenated, etc.

So, for anyone attempting this: Think about solutions for the bottom rows first (where the nasty nested loops are), the top rows will be the easier part.
