### ISSUE TITLE
Proxy users

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1304]
UserProfiles should get an additional flag `Proxy user` which, if set
- prevents them from being deleted on user bulk deletion
- removes them from user selection fields for all users but staff (i.e., in the user profile delegate selection, delegate course form and contribution form)

**Comment by He3lixxx** [comment]
@velramiir wants to do this. Can not yet assign, as we're waiting for him to accept the collaboration invitation.

**Comment by janno42** [comment]
it would be perfect if the text answer visibility tooltips could be changed for proxy users. if a proxy user is in the list of people who can see the text answers, the name of this proxy user and number of its delegates should be shown together. the delegates should not be counted again for the number of delegates shown after the list of names.

`These text answers can be seen by: Fachschaftsrat, 8 delegates and the evaluation team.`
would then instead be
`These text answers can be seen by: Fachschaftsrat (8 people) and the evaluation team.`,

`These text answers can be seen by: Prof. Dr. responsible, Proxy user, 4 delegates and the evaluation team.`
could be
`These text answers can be seen by: Prof. Dr. responsible, Proxy user (2 people), 2 delegates and the evaluation team.`
