### ISSUE TITLE
Remove vote_start_datetime error for contributors

### ISSUE THREAD

**Issue by tzwenn** [fsr-de/EvaP#1312]
When approving an exam evaluation as lecturer, the "Beginn der Evaluierung" field is prefilled with `<current day> 08:00`.
As I was (wt 2018/19) notified of the pending approval just after this time, this default value gives me a form validation error when not manually adjusted.

![screen shot 2019-02-20 at 10 24 32](https://user-images.githubusercontent.com/495690/53081345-f649a280-34fa-11e9-9751-7d2cdc359985.png)

**Comment by janno42** [comment]
thanks for informing us. that actually was a user error by the evaluation team - the beginning time should have been set later that day. the problem should not occur in non-experimental same day rush starts :)
it is intended that contributors can't set the beginning date to the past.

**Comment by tzwenn** [comment]
👍

**Comment by tzwenn** [comment]
Maybe this can still be fixed in code: When a lecture/exam is not approved, it can't be evaluated. (Can it?) Why then offer any date in the past? Maybe just prefill this field with "now + X"?

**Comment by janno42** [comment]
good point. automatically setting values feels a bit weird, but in this case it shouldn't cause any problems.
`vote_start_datetime` should be set to `now` on saving the contributor course edit form when the entered value is in the past.

**Comment by janno42** [comment]
We decided to just remove the form error for contributors. Dates can then be saved also if they are in the past.

**Comment by He3lixxx** [comment]
Fixed in #1324
