### ISSUE TITLE
landing page displays wrong state (in split lecture+exam view)

### ISSUE THREAD

**Issue by tzwenn** [fsr-de/EvaP#1313]
Although the evaluation period passed, one of my lectures is still displayed as "in evaluation".
I can't remember this behavior before, so it might be due to the new lecture+exam view.
![screen shot 2019-02-20 at 10 44 56](https://user-images.githubusercontent.com/495690/53082233-b683ba80-34fc-11e9-9ec4-d9f3d992f625.png)

**Comment by janno42** [comment]
after updating the production instance we forgot to update the cronjobs accordingly, so some evaluations states haven't been updated this morning. that should be fixed now :)
