### ISSUE TITLE
Evaluation preview button visibility

### ISSUE THREAD

**Issue by MrSerth** [fsr-de/EvaP#1314]
As a teaching assistant, I might be a contributor to a given course and therefore get my own feedback in the main evaluation. If that course also has an exam evaluation, I see that listed on my "own evaluations" page with the option to preview the questionnaire. However, as not being responsible, I miss the access rights to preview the linked page, resulting in an error.

I would like to either don't have the preview button (it already knows while rendering that page that I am not a contributor, shown through the corresponding icon next to the exam evaluation title) or to give me the rights to preview the questionnaire.

**Comment by janno42** [comment]
The preview page should be available for all responsibles and contributors. All of these users should see the button to the preview page. If a user is not responsible for the evaluation's course and is not a contributor in this evaluation there should be no button and the page should not be accessible.
