### ISSUE TITLE
Autocompletion for manage.py

### ISSUE THREAD

**Issue by He3lixxx** [fsr-de/EvaP#1328]
Since we're running inside a vm, we can easily manipulate the auto-completion of the bash running to also autocomplete the commands that manage.py provides. There are some rather hacky python scripts that allow to dynamically generate the auto completion from the argparser. I think they are too heavyweight for this, we probably just want to add a simple file for the bash completion that allows it to autocomplete with what manage.py prints when you call it without arguments.

See https://askubuntu.com/questions/68175/how-to-create-script-with-auto-complete

**Comment by janno42** [comment]
implemented in #1334
