### ISSUE TITLE
It is possible to reconstruct the votes of the first voter

### ISSUE THREAD

**Issue by karyon** [fsr-de/EvaP#1335]
(This assumes that sequential primary keys are used. Also, you need DB access to do this.)

It is possible to find out the order in which people voted by looking at the primary keys of the voters table (which is a relation between UserProfile and Evaluation)

Furthermore, it is possible to find out what the first voter for an evaluation voted by looking at the primary keys of the RatingAnswerCounters for that evaluation. This is possible because evaluations start with no RatingAnswerCounters, those get created on demand when the respective value gets a vote.

If a course only has two voters, the votes of the second voter are reconstructible as well. For courses of arbitrary sizes, the voters of the first few voters might be reconstructible if they gave different answers from the previous voters (so, in the worst case, the answers of the first 2/5/7 voters might be reconstructible depending on the question type)

Possible solutions are:
* Use UUIDs for the pk of RatingAnswerCounter similar to https://github.com/fsr-itse/EvaP/pull/1002
* always create all the counters for each question/contribution (e.g. when starting the evaluation or on the first vote)
    * an optimization for this might be to use the (postgres-specific) [ArrayField](https://docs.djangoproject.com/en/2.2/ref/contrib/postgres/fields/#arrayfield)

**Comment by He3lixxx** [comment]
We decided that uuids in combination with a cronjob that [re-clusters the database](https://www.postgresql.org/docs/9.1/sql-cluster.html) are probably enough solution (having in mind that someone with shell access to the server can find out votes from that moment on anyway)

**Comment by He3lixxx** [comment]
Handled in code with #1341. Can be closed as soon as the cronjob described in the wiki (https://github.com/fsr-de/EvaP/wiki/Installation#database-clustering) is applied

**Comment by janno42** [comment]
clustering done on production
