### ISSUE TITLE
Clean duplicates on user import

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1337]
When importing a list of users that includes the same person multiple times, these duplicates should be ignored during the import (a message for each ignored user could be shown). Currently the importer throws an exception.

**Comment by janno42** [comment]
@felixrindt do you plan to continue working on this issue?

**Comment by felixrindt** [comment]
That's would I would like to look into today :)

**Comment by felixrindt** [comment]
So I already did https://github.com/fsr-de/EvaP/pull/1344
but people preferred a rework of the import system. I'm not sure wether I have a long enough attention span for that.
