### ISSUE TITLE
Allow courses to habe a subtitle / complete title.

### ISSUE THREAD

**Issue by christianzoellner** [fsr-de/EvaP#1354]
Some courses (e.g. bachelor projects or project seminars at HPI) tend to have very long titles, which makes some course lists less readable.

It would be nice to have the full titles somewhere (e.g. in the details view) but only see a short title when scrolling though the list to make it compact.

An alternative that covers some cases is to allow for a separate subtitle that is only shown in some views.
Alternatively, the full name could be shortened with "..." in the list view.

**Comment by felixrindt** [comment]
Also, one could consider nicknames like LinA, PT, TI, ...
Although having two names for a course should be an exception, as it adds work to the import process.

**Comment by janno42** [comment]
we talked about the feature request and came to the opinion that managing the short titles would add too much overhead and would add additional ui complexity that we'd like to avoid. so this issue will be closed.
