### ISSUE TITLE
[Feature Proposal] Embed EvaP Ratings on official HPI course pages with a plugin

### ISSUE THREAD

**Issue by ramboldio** [fsr-de/EvaP#1369]
When choosing courses, switching back and forth between hpi.de, the websites of the chairs, EvaP and the time table is a tedious procedure. By embedding the results directly on the official websites the visibility of the results could be increased.

this can be achieved by direct integration with hpi.de, a browser plugin or a forward proxy where the user only has to change the URL slightly:
eg. changing

`hpi.de/studium/lehrveranstaltungen/it-systems-engineering-ma/etc/etc`

to

`evap.hpi.de/studium/lehrveranstaltungen/it-systems-engineering-ma/etc/etc`

would give you a modified page with the ratings when logged in.

**Comment by janno42** [comment]
see also comments in #313 about course series grouping, which would probably be required for this feature, as some courses change names from time to time.

**Comment by janno42** [comment]
we (the evaluation team of the student representative group) see the advantage that an integrated result display can have. on the other hand there are some disadvantages as well:
- ideally there should be a way to group courses into series as mentioned above to have an accurate mapping. some courses change names, some courses are held by different lecturers each year - this would need to be dealt with first.
- similar to the feature requested in #806 we don't see a primary use case of evap in using the evaluation results as the basis for making a decision which courses to take in the next semester. they can be used as one source if people want to use this information but they shouldn't use them as the main factor.
- evaluation results are only displayed to logged in users. the course pages are publicly available - so people would have to log in somehow before accessing the information from evap. mirroring the course pages and adding additional information is a bit strange, we don't want to present information from "third parties" on our page.

we came to the conclusion that implementing the integration seems to require a lot of effort (which would probably also not be entirely in our hands). searching for a specific course on the results page is quite easy in our opinion and it's hard to argue that not having to use one additional tab for the search on evap is worth the troubles with the integration into other websites.
i'll close this issue but you are welcome to contact the student representatives about this idea if you think it should be discussed further. as it is foremost a decision to be made by the student representatives, github is not the place where we would deepen the discussion.
