### ISSUE TITLE
Error message if course already exists on import

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1390]
When importing enrollment data including at least one course with a name that already exists for this semester in the database, the importer fails silently. This shouldn't be the case.
The test import should display an error message if a course with the same (German or English) name already exists in the current semester.

There should also be a test for that.

**Comment by niklasmohrin** [comment]
In EnrollmentImporter.check_evaluation_data_correctness(), there is this line:
```python
already_exists = Evaluation.objects.filter(course__semester=semester, name_de=evaluation_data.name_de).exists()
```
It only checks for German names, maybe this has something to do with it.
