### ISSUE TITLE
Add confirmation for login with login key

### ISSUE THREAD

**Issue by janno42** [fsr-de/EvaP#1393]
External users can login by clicking on the login URL sent to them via email. Before users are actually authenticated on the platform after clicking on this link, they should have to confirm the login by, e.g., clicking a confirmation button in a modal or on a designated page.

This prevents cases in which the URL is already requested for, e.g., a preview of the page and thus invalidates the login key which results in a new link being sent when users actively click on the link (which is then already the second GET request).

**Comment by felixrindt** [comment]
Why not invalidate the key when navigating away from the page the invite link leads to? That way, there is no additional step.

**Comment by janno42** [comment]
then we'd have to add authentication logic on some random page which doesn't seem optimal. i think one click on "I want to log in as John Doe" is perfectly fine.

**Comment by karyon** [comment]
fwiw, https://stackoverflow.com/questions/41699071/bingpreview-invalidates-one-time-links-in-email/42525744. i suspect that's the reason why this is happening and personally i would prefer a targeted solution, and not degrade the experience of all because some email client is misbehaving.
